"use client"

// components/ImageScroller.js
import Image from "next/image";
import { useState } from "react";
import Trending from "./Trending";
const images = [
  { src: "/film1.webp", svg: "/one.svg",color:"#aa150f" ,alt: "image 1", para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, modi doloremque. Dolorum, excepturi accusamus cum ex obcaecati, debitis quasi, repellat assumenda sapiente impedit praesentium ipsa distinctio molestiae. Blanditiis et voluptate quidem optio doloribus dolorem, iusto non nemo repellendus quas unde quibusdam mollitia vero numquam ut ducimus rem ad sapiente veniam maxime. Voluptate accusamus explicabo id esse, dolores expedita quos voluptatibus. Tenetur suscipit aspernatur pariatur ullam fugit error, voluptates molestiae fuga, commodi, deleniti dolore vel consequuntur. Libero quibusdam asperiores maxime distinctio dolor ipsum dignissimos, expedita amet saepe repellat earum corrupti officia quis qui excepturi recusandae sapiente, nam accusantium similique illum impedit consectetur fuga dolores odio? Doloremque maxime, vitae beatae fugit enim quo veniam tempore nulla nemo quia, labore, aperiam adipisci officiis minus rem! Voluptatibus molestiae esse voluptatum dolor quod, doloremque autem a consequuntur reprehenderit praesentium doloribus temporibus, explicabo tempore nobis eligendi consequatur assumenda veritatis ullam fugiat error aspernatur. Obcaecati ex, dolor veritatis ratione exercitationem mollitia ab nesciunt iure est doloremque! Cumque iure beatae aliquid est, voluptas obcaecati delectus, labore maiores atque odit a quia mollitia adipisci dolorum odio tempore error eveniet! Magnam, eligendi illum in laborum pariatur cupiditate quasi eaque. Earum, tempore et facere laboriosam amet perferendis deleniti, voluptates quibusdam eius quos aliquam officiis soluta. Harum hic, quidem nam veritatis molestias fugit numquam nesciunt incidunt sunt inventore beatae perferendis fuga quas eius deserunt facere. Eveniet ex officiis ea sunt autem magnam animi deserunt sapiente ipsa vitae corporis accusamus, aliquid alias, quibusdam laborum enim provident saepe, labore minima et cupiditate molestias reprehenderit hic. Explicabo laboriosam autem ut qui, quibusdam, molestias aut sapiente mollitia eaque expedit " },
  { src: "/film2.webp", svg: "/two.svg",color:"#bf8a49" ,alt: "image 2" , para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, modi doloremque. Dolorum, excepturi accusamus cum ex obcaecati, debitis quasi, repellat assumenda sapiente impedit praesentium ipsa distinctio molestiae. Blanditiis et voluptate quidem optio doloribus dolorem, iusto non nemo repellendus quas unde quibusdam mollitia vero numquam ut ducimus rem ad sapiente veniam maxime. Voluptate accusamus explicabo id esse, dolores expedita quos voluptatibus. Tenetur suscipit aspernatur pariatur ullam fugit error, voluptates molestiae fuga, commodi, deleniti dolore vel consequuntur. Libero quibusdam asperiores maxime distinctio dolor ipsum dignissimos, expedita amet saepe repellat earum corrupti officia quis qui excepturi recusandae sapiente, nam accusantium similique illum impedit consectetur fuga dolores odio? Doloremque maxime, vitae beatae fugit enim quo veniam tempore nulla nemo quia, labore, aperiam adipisci officiis minus rem! Voluptatibus molestiae esse voluptatum dolor quod, doloremque autem a consequuntur reprehenderit praesentium doloribus temporibus, explicabo tempore nobis eligendi consequatur assumenda veritatis ullam fugiat error aspernatur. Obcaecati ex, dolor veritatis ratione exercitationem mollitia ab nesciunt iure est doloremque! Cumque iure beatae aliquid est, voluptas obcaecati delectus, labore maiores atque odit a quia mollitia adipisci dolorum odio tempore error eveniet! Magnam, eligendi illum in laborum pariatur cupiditate quasi eaque. Earum, tempore et facere laboriosam amet perferendis deleniti, voluptates quibusdam eius quos aliquam officiis soluta. Harum hic, quidem nam veritatis molestias fugit numquam nesciunt incidunt sunt inventore beatae perferendis fuga quas eius deserunt facere. Eveniet ex officiis ea sunt autem magnam animi deserunt sapiente ipsa vitae corporis accusamus, aliquid alias, quibusdam laborum enim provident saepe, labore minima et cupiditate molestias reprehenderit hic. Explicabo laboriosam autem ut qui, quibusdam, molestias aut sapiente mollitia eaque expedit"
 },
  { src: "/film4.webp", svg: "/4.svg",color:"#302f3d" ,alt: "image 4" , para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, modi doloremque. Dolorum, excepturi accusamus cum ex obcaecati, debitis quasi, repellat assumenda sapiente impedit praesentium ipsa distinctio molestiae. Blanditiis et voluptate quidem optio doloribus dolorem, iusto non nemo repellendus quas unde quibusdam mollitia vero numquam ut ducimus rem ad sapiente veniam maxime. Voluptate accusamus explicabo id esse, dolores expedita quos voluptatibus. Tenetur suscipit aspernatur pariatur ullam fugit error, voluptates molestiae fuga, commodi, deleniti dolore vel consequuntur. Libero quibusdam asperiores maxime distinctio dolor ipsum dignissimos, expedita amet saepe repellat earum corrupti officia quis qui excepturi recusandae sapiente, nam accusantium similique illum impedit consectetur fuga dolores odio? Doloremque maxime, vitae beatae fugit enim quo veniam tempore nulla nemo quia, labore, aperiam adipisci officiis minus rem! Voluptatibus molestiae esse voluptatum dolor quod, doloremque autem a consequuntur reprehenderit praesentium doloribus temporibus, explicabo tempore nobis eligendi consequatur assumenda veritatis ullam fugiat error aspernatur. Obcaecati ex, dolor veritatis ratione exercitationem mollitia ab nesciunt iure est doloremque! Cumque iure beatae aliquid est, voluptas obcaecati delectus, labore maiores atque odit a quia mollitia adipisci dolorum odio tempore error eveniet! Magnam, eligendi illum in laborum pariatur cupiditate quasi eaque. Earum, tempore et facere laboriosam amet perferendis deleniti, voluptates quibusdam eius quos aliquam officiis soluta. Harum hic, quidem nam veritatis molestias fugit numquam nesciunt incidunt sunt inventore beatae perferendis fuga quas eius deserunt facere. Eveniet ex officiis ea sunt autem magnam animi deserunt sapiente ipsa vitae corporis accusamus, aliquid alias, quibusdam laborum enim provident saepe, labore minima et cupiditate molestias reprehenderit hic. Explicabo laboriosam autem ut qui, quibusdam, molestias aut sapiente mollitia eaque expedit" },
  { src: "/film6.webp", svg: "/6.svg",color:"#15413b" ,alt: "image 6" , para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, modi doloremque. Dolorum, excepturi accusamus cum ex obcaecati, debitis quasi, repellat assumenda sapiente impedit praesentium ipsa distinctio molestiae. Blanditiis et voluptate quidem optio doloribus dolorem, iusto non nemo repellendus quas unde quibusdam mollitia vero numquam ut ducimus rem ad sapiente veniam maxime. Voluptate accusamus explicabo id esse, dolores expedita quos voluptatibus. Tenetur suscipit aspernatur pariatur ullam fugit error, voluptates molestiae fuga, commodi, deleniti dolore vel consequuntur. Libero quibusdam asperiores maxime distinctio dolor ipsum dignissimos, expedita amet saepe repellat earum corrupti officia quis qui excepturi recusandae sapiente, nam accusantium similique illum impedit consectetur fuga dolores odio? Doloremque maxime, vitae beatae fugit enim quo veniam tempore nulla nemo quia, labore, aperiam adipisci officiis minus rem! Voluptatibus molestiae esse voluptatum dolor quod, doloremque autem a consequuntur reprehenderit praesentium doloribus temporibus, explicabo tempore nobis eligendi consequatur assumenda veritatis ullam fugiat error aspernatur. Obcaecati ex, dolor veritatis ratione exercitationem mollitia ab nesciunt iure est doloremque! Cumque iure beatae aliquid est, voluptas obcaecati delectus, labore maiores atque odit a quia mollitia adipisci dolorum odio tempore error eveniet! Magnam, eligendi illum in laborum pariatur cupiditate quasi eaque. Earum, tempore et facere laboriosam amet perferendis deleniti, voluptates quibusdam eius quos aliquam officiis soluta. Harum hic, quidem nam veritatis molestias fugit numquam nesciunt incidunt sunt inventore beatae perferendis fuga quas eius deserunt facere. Eveniet ex officiis ea sunt autem magnam animi deserunt sapiente ipsa vitae corporis accusamus, aliquid alias, quibusdam laborum enim provident saepe, labore minima et cupiditate molestias reprehenderit hic. Explicabo laboriosam autem ut qui, quibusdam, molestias aut sapiente mollitia eaque expedit"},
  { src: "/film8.webp", svg: "/8.svg",color:"#c6451c" ,alt: "image 8" , para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, modi doloremque. Dolorum, excepturi accusamus cum ex obcaecati, debitis quasi, repellat assumenda sapiente impedit praesentium ipsa distinctio molestiae. Blanditiis et voluptate quidem optio doloribus dolorem, iusto non nemo repellendus quas unde quibusdam mollitia vero numquam ut ducimus rem ad sapiente veniam maxime. Voluptate accusamus explicabo id esse, dolores expedita quos voluptatibus. Tenetur suscipit aspernatur pariatur ullam fugit error, voluptates molestiae fuga, commodi, deleniti dolore vel consequuntur. Libero quibusdam asperiores maxime distinctio dolor ipsum dignissimos, expedita amet saepe repellat earum corrupti officia quis qui excepturi recusandae sapiente, nam accusantium similique illum impedit consectetur fuga dolores odio? Doloremque maxime, vitae beatae fugit enim quo veniam tempore nulla nemo quia, labore, aperiam adipisci officiis minus rem! Voluptatibus molestiae esse voluptatum dolor quod, doloremque autem a consequuntur reprehenderit praesentium doloribus temporibus, explicabo tempore nobis eligendi consequatur assumenda veritatis ullam fugiat error aspernatur. Obcaecati ex, dolor veritatis ratione exercitationem mollitia ab nesciunt iure est doloremque! Cumque iure beatae aliquid est, voluptas obcaecati delectus, labore maiores atque odit a quia mollitia adipisci dolorum odio tempore error eveniet! Magnam, eligendi illum in laborum pariatur cupiditate quasi eaque. Earum, tempore et facere laboriosam amet perferendis deleniti, voluptates quibusdam eius quos aliquam officiis soluta. Harum hic, quidem nam veritatis molestias fugit numquam nesciunt incidunt sunt inventore beatae perferendis fuga quas eius deserunt facere. Eveniet ex officiis ea sunt autem magnam animi deserunt sapiente ipsa vitae corporis accusamus, aliquid alias, quibusdam laborum enim provident saepe, labore minima et cupiditate molestias reprehenderit hic. Explicabo laboriosam autem ut qui, quibusdam, molestias aut sapiente mollitia eaque expedit."},
  { src: "/film9.webp", svg: "/9.svg",color:"#4cb882" ,alt: "image 9" , para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, modi doloremque. Dolorum, excepturi accusamus cum ex obcaecati, debitis quasi, repellat assumenda sapiente impedit praesentium ipsa distinctio molestiae. Blanditiis et voluptate quidem optio doloribus dolorem, iusto non nemo repellendus quas unde quibusdam mollitia vero numquam ut ducimus rem ad sapiente veniam maxime. Voluptate accusamus explicabo id esse, dolores expedita quos voluptatibus. Tenetur suscipit aspernatur pariatur ullam fugit error, voluptates molestiae fuga, commodi, deleniti dolore vel consequuntur. Libero quibusdam asperiores maxime distinctio dolor ipsum dignissimos, expedita amet saepe repellat earum corrupti officia quis qui excepturi recusandae sapiente, nam accusantium similique illum impedit consectetur fuga dolores odio? Doloremque maxime, vitae beatae fugit enim quo veniam tempore nulla nemo quia, labore, aperiam adipisci officiis minus rem! Voluptatibus molestiae esse voluptatum dolor quod, doloremque autem a consequuntur reprehenderit praesentium doloribus temporibus, explicabo tempore nobis eligendi consequatur assumenda veritatis ullam fugiat error aspernatur. Obcaecati ex, dolor veritatis ratione exercitationem mollitia ab nesciunt iure est doloremque! Cumque iure beatae aliquid est, voluptas obcaecati delectus, labore maiores atque odit a quia mollitia adipisci dolorum odio tempore error eveniet! Magnam, eligendi illum in laborum pariatur cupiditate quasi eaque. Earum, tempore et facere laboriosam amet perferendis deleniti, voluptates quibusdam eius quos aliquam officiis soluta. Harum hic, quidem nam veritatis molestias fugit numquam nesciunt incidunt sunt inventore beatae perferendis fuga quas eius deserunt facere. Eveniet ex officiis ea sunt autem magnam animi deserunt sapiente ipsa vitae corporis accusamus, aliquid alias, quibusdam laborum enim provident saepe, labore minima et cupiditate molestias reprehenderit hic. Explicabo laboriosam autem ut qui, quibusdam, molestias aut sapiente mollitia eaque expedit"},
  { src: "/film10.webp", svg: "/10.svg",color:"#a2984a" ,alt: "image 10" , para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis, modi doloremque. Dolorum, excepturi accusamus cum ex obcaecati, debitis quasi, repellat assumenda sapiente impedit praesentium ipsa distinctio molestiae. Blanditiis et voluptate quidem optio doloribus dolorem, iusto non nemo repellendus quas unde quibusdam mollitia vero numquam ut ducimus rem ad sapiente veniam maxime. Voluptate accusamus explicabo id esse, dolores expedita quos voluptatibus. Tenetur suscipit aspernatur pariatur ullam fugit error, voluptates molestiae fuga, commodi, deleniti dolore vel consequuntur. Libero quibusdam asperiores maxime distinctio dolor ipsum dignissimos, expedita amet saepe repellat earum corrupti officia quis qui excepturi recusandae sapiente, nam accusantium similique illum impedit consectetur fuga dolores odio? Doloremque maxime, vitae beatae fugit enim quo veniam tempore nulla nemo quia, labore, aperiam adipisci officiis minus rem! Voluptatibus molestiae esse voluptatum dolor quod, doloremque autem a consequuntur reprehenderit praesentium doloribus temporibus, explicabo tempore nobis eligendi consequatur assumenda veritatis ullam fugiat error aspernatur. Obcaecati ex, dolor veritatis ratione exercitationem mollitia ab nesciunt iure est doloremque! Cumque iure beatae aliquid est, voluptas obcaecati delectus, labore maiores atque odit a quia mollitia adipisci dolorum odio tempore error eveniet! Magnam, eligendi illum in laborum pariatur cupiditate quasi eaque. Earum, tempore et facere laboriosam amet perferendis deleniti, voluptates quibusdam eius quos aliquam officiis soluta. Harum hic, quidem nam veritatis molestias fugit numquam nesciunt incidunt sunt inventore beatae perferendis fuga quas eius deserunt facere. Eveniet ex officiis ea sunt autem magnam animi deserunt sapiente ipsa vitae corporis accusamus, aliquid alias, quibusdam laborum enim provident saepe, labore minima et cupiditate molestias reprehenderit hic. Explicabo laboriosam autem ut qui, quibusdam, molestias aut sapiente mollitia eaque expedit"},
];

export default function ImageScroller() {

    const [show, setshow] = useState(null);

  function handleClick(idx) {
    setshow(idx);
  }

  return (
    <>
    <div className="flex overflow-x-auto space-x-4 px-4 py-2 mt-6 pb-2.5">
      {images.map((img, idx) => (
        <div
          key={idx}
           onClick={()=>{handleClick(idx)}}
          className="grid grid-cols-[24px_36px_148px] grid-rows-[121px_98px_24px] flex-shrink-0"
        >
          <Image
            src={img.src}
            alt={img.alt}
            width={184}
            height={242}
            className="col-start-2 col-end-4 row-start-1 row-end-4 rounded-[23px] cursor-pointer w-[184px] h-[242px]"
          />
          <Image
            src={img.svg}
            alt={`${img.alt} overlay`}
            width={64}
            height={120}
            className="col-start-1 col-end-3 row-start-2 row-end-3 w-[64px] h-[120px]"
          />
        </div>

       
      ))}

        {show !== null && (
        <Trending Imgsrc={images[show].src} show={show} setshow={setshow} color={images[show].color} para ={images[show].para}/>
      )}
    </div>


    </>
  );
}
